In [2]:
from __future__ import print_function
import torch

In [4]:
x = torch.empty(3, 5)
print(x)

tensor(1.00000e-44 *
       [[ 0.0000,  0.0000,  0.0000,  0.0000,  3.6434],
        [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000]])


In [6]:
y = torch.rand(5, 7)
print(y)

tensor([[ 0.3344,  0.0161,  0.9993,  0.5554,  0.4608,  0.4893,  0.9801],
        [ 0.3785,  0.0164,  0.1003,  0.5588,  0.2999,  0.7457,  0.4044],
        [ 0.5115,  0.8663,  0.9083,  0.9291,  0.7095,  0.1292,  0.5046],
        [ 0.9969,  0.3748,  0.2376,  0.7737,  0.0585,  0.7560,  0.0419],
        [ 0.4613,  0.1206,  0.3670,  0.6867,  0.8696,  0.2045,  0.8815]])


In [7]:
z = torch.zeros(2, 7, dtype=torch.long)
print(z)

tensor([[ 0,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0,  0]])


In [9]:
q = torch.ones(9, dtype=torch.double)
r = q.numpy()
print(r)
print(torch.from_numpy(r))

[1. 1. 1. 1. 1. 1. 1. 1. 1.]
tensor([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.], dtype=torch.float64)


In [11]:
torch.Tensor.requires_grad = True

In [1]:
from model import Net
net = Net()
print(net)

Net(
  (conv1): Conv2d(4, 64, kernel_size=(3, 3), stride=(1, 1))
  (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1))
  (conv3): Conv2d(64, 128, kernel_size=(3, 3), stride=(1, 1))
  (conv4): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1))
  (fc1): Linear(in_features=1152, out_features=256, bias=True)
  (fc2): Linear(in_features=256, out_features=256, bias=True)
  (fc3): Linear(in_features=256, out_features=5, bias=True)
)


In [4]:
params = list(net.parameters())
print(len(params))
print(params[0].size())

14
torch.Size([64, 4, 3, 3])
